export const MESSAGE_TYPES = {
  TRANSLATE_WORD: "LINGUAFLOW_TRANSLATE_WORD",
  TRANSLATE_BATCH: "LINGUAFLOW_TRANSLATE_BATCH",
  GET_SETTINGS: "LINGUAFLOW_GET_SETTINGS",
  SETTINGS_UPDATED: "LINGUAFLOW_SETTINGS_UPDATED",
  SAVE_VOCABULARY: "LINGUAFLOW_SAVE_VOCABULARY",
  IMPORT_VOCABULARY: "LINGUAFLOW_IMPORT_VOCABULARY",
  MARK_REVIEWED: "LINGUAFLOW_MARK_REVIEWED",
  CACHE_CLEAR: "LINGUAFLOW_CACHE_CLEAR",
  TEST_CONNECTION: "LINGUAFLOW_TEST_CONNECTION",
  GET_PAGE_VOCAB: "LINGUAFLOW_GET_PAGE_VOCAB",
  GET_ERRORS: "LINGUAFLOW_GET_ERRORS",
  CLEAR_ERRORS: "LINGUAFLOW_CLEAR_ERRORS",
} as const;

export const SKIP_TAGS = new Set([
  "SCRIPT", "STYLE", "CODE", "PRE", "TEXTAREA", "INPUT", "SELECT", "OPTION",
  "NOSCRIPT", "IFRAME", "SVG", "CANVAS", "VIDEO", "AUDIO", "OBJECT",
  "EMBED", "MATH", "HEAD", "LINK", "META", "TITLE",
  "NAV", "FOOTER", "BUTTON",
]);

export const SKIP_CLASSES = [
  "linguaflow",
  "code",
  "pre",
  "linenumber",
  "line-number",
  "hljs",
  "syntax-highlighter",
  "prism",
  "CodeMirror",
  "monaco-editor",
];

export const SKIP_ATTRS = [
  "contenteditable",
  "data-linguaflow-skip",
];

export const SPACED_REPETITION_INTERVALS = [
  1 * 24 * 60 * 60 * 1000,
  3 * 24 * 60 * 60 * 1000,
  7 * 24 * 60 * 60 * 1000,
  14 * 24 * 60 * 60 * 1000,
  30 * 24 * 60 * 60 * 1000,
];
